version: '2'

services:
  web:
    image: you_group/project_name:latest
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - ./www:/var/www
    depends_on:
      - project_name_mysql
      - redis

  project_name_mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data_5.6:/var/lib/mysql:rw

  redis:
    image: redis
    ports:
      - "6379:6379"

  solr:
    image: guywithnose/solr:4.9.0
    ports:
     - "8983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/mycores

volumes:
  solr_data:
  mysql_data_5.6: