version: '2'

services:
  web:
    image: you_group/project_name:latest
    ports:
      - "80:80"
      - "443:443"
      - "873:873"
    depends_on:
      - project_name_mysql
      - redis
      - elasticsearch
    volumes:
      - project-data-sync:/var/www/html:rw
  project_name_mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data_5.6:/var/lib/mysql:rw
  redis:
    image: redis
    ports:
      - "6379:6379"
  elasticsearch:
    image: itzg/elasticsearch:2.4.x
    ports:
      - "9200:9200"
      - "9300:9300"
volumes:
  mysql_data_5.6:
  project-data-sync:
    external: true